Update config.yml
Teaching-projects/SZE-MoSzE-2019-Arkona pull request #6
Opened 2019-10-14 18:23 UTC by phenyo97

config.yml changed, available for test.

2019-10-14 22:04 UTC, hegyhati requested changes
A kodot most nem neztem meg, de ha van meg mas, ami a mult hetig hianyzik, azt is keretik megcsinalni.

2019-10-14 22:04 UTC, hegyhati commented on .circleci/config.yml
> +        - run: g++ -std=c++11 *.cpp *.h
minek forditjuk ujra le? inkabb rantsuk elo azt, ami a buildben elkeszult.

2019-10-14 22:04 UTC, hegyhati commented on .circleci/config.yml
> +        - run: g++ -std=c++11 *.cpp *.h #build the project
Ennek a resznek mar a make file-lal kellene tortennie.

2019-10-14 22:04 UTC, hegyhati commented on .circleci/config.yml
> +    print:
Ez a lepes POC-nek jo volt, de ki lehet torolni mar

2019-10-14 22:04 UTC, hegyhati commented on .circleci/config.yml
> +        - run: ls -la
ilyen szemeteket ne hagyjunk benne.

2019-10-14 22:04 UTC, hegyhati commented on .circleci/config.yml
> +        - run: g++ -std=c++11 *.cpp *.h
lasd fentebb

2019-10-14 22:04 UTC, hegyhati commented on .circleci/config.yml
> +        - run: pwd
???

2019-10-23 09:32 UTC, phenyo97 commented on .circleci/config.yml
> +        - run: g++ -std=c++11 *.cpp *.h
javítás megtörtént

2019-10-23 09:32 UTC, phenyo97 commented on .circleci/config.yml
> +        - run: g++ -std=c++11 *.cpp *.h #build the project
makfile elkészült és használva van

2019-10-23 09:33 UTC, phenyo97 commented on .circleci/config.yml
> +    print:
törlésre került

2019-10-23 09:33 UTC, phenyo97 commented on .circleci/config.yml
> +        - run: ls -la
a szemetek mindenhonnan eltávolításra kerültek

2019-10-23 09:33 UTC, phenyo97 commented on .circleci/config.yml
> +        - run: g++ -std=c++11 *.cpp *.h
megoldva

2019-10-23 09:34 UTC, phenyo97 commented on .circleci/config.yml
> +        - run: pwd
törölve

2019-10-31 13:45 UTC, phenyo97 commented
@hegyhati módosítva a kért dolgok, makefile felkelül és azzal működik már

2019-10-31 13:50 UTC, hegyhati approved these changes

2019-10-31 13:50 UTC, merged