Relative path
Teaching-projects/SZE-MoSzE-2019-Arkona pull request #7
Opened 2019-10-14 21:01 UTC by Kearmin

Added relative path support to commands

2019-10-14 23:04 UTC, hegyhati requested changes
Jol megcsamcsogtam. Nyilvan vannak komolyabb es kevesbe komoly, stilisztikai dolgok is.

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +    return true;
ter ez vissza barmi massal?

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +void printIndents(int indent)
std::setw

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +        if( *file == *f){
Az elobb meg nev alapjan teszteltel.

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +    }
Ez a logika ketszer is megvan. Itt meg az mkdir-ben is.

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +    while(it != directories.end()){
miert nem for? es ha mar itt tartunk, ez szerintem elszall vegtelen looppal

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +    }
ua

2019-10-14 23:04 UTC, hegyhati commented on directory.cpp
> +Directory* Directory::contains(string dirname) const
miert nem containsDirectory, hogy konzisztens legyen az elnevezes?

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    cout << "\n$ ";
\n minek?

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +}
Jujj....

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    ss >> path;
that's not how mkdir works.

nem `mkdir name /foo/bar/../ize/` hanem `mkdir /foo/bar/../ize/name`

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    ss >> path;
ua

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +        if( arg[i] == '/'){
na, ha az elobb mar egy beepitett string fuggvennyel meg tudtad keresni, hogy van-e benne / , akkor most ne jard mar be karakterenkent.

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    }
ezt miert?

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    }
kicsit logikatlanul felepitett dolgok. Az ember ugy gondolna, hogy a contains az egy bool-t ad vissza. A cdToDirectory meg monjduk egy string-et varna.

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    if (directoryName == "..") {
kb erre valo lenne az else if.

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +    currentDirectory = currentLocation.back();
redundansan megtartani a kettot eleg nagy bugveszely. Ha egy helyen valahol nem egyutt update-eled oket, akkor felrecsuszik minden.

2019-10-14 23:04 UTC, hegyhati commented on filesystem.cpp
> +            cout << "Cannot remove: '" << dirToDelete->getNameRaw() << "' it is a directory\n";
az rm letorli a konyvtarakat is, azzal nincs baja. Azzal van, ha nem ures.

2019-10-14 23:04 UTC, hegyhati commented on filesystem.h
>      bool cdToDirectory(Directory* newLocation);
typic peldaja az ilyen elburjanzott takolt dolgoknak. Van 5 db cd fuggveny, ebbol 4 voidot ad vissza, d evan egy bool, a kovetelt argumentumokban is eleg valtozatosak.  Nem latszik, hogy melyik mit kezel pontosan le, Lehet jo volna kicsit atgondolni, refaktoralni.  Pl csak erre ranezve, az ember mondhatna, hogy a `cdRoot` az csak egy `cdRelativePath("/")`, hasonlokeppen a parentre.

2019-11-17 19:19 UTC, Kearmin commented
Ahol tudtam refakrotáltam a kódot, és a hibákat javítottam. Pl. redundanciát vettem ki , cd-t kicsit leegyszerűsítettem, név check-elés mindhol overloadolt operatorokkal van, függvények nevét konzistessebbé tettem

2019-11-18 15:44 UTC, hegyhati requested changes
CSomo minden nem lett kijavitva amit korabban irtam, illetve nem latom, hogy le lenne tesztelve a relative path-os dolog a CI-ban.

2019-11-18 15:44 UTC, hegyhati commented on directory.h
>          return d.name == this->name;
EGyreszt egy file hogy lenne mar egyenlo egy directory-val? 
Masreszt attol meg hogy ket directory-nak a neve megegyezik, attol biztos, hogy egyenlo? marmint mire hasznalod ezt? ha ket alkonyvtar mindegyikeben van egy `alma` alkonyvtar, akkor azok nem ugyanazok.

2019-11-18 15:44 UTC, hegyhati commented on file.h
> +    }
ez baromi csunya igy amugy , hogy pointerre meg adatra is megcsinalod. Inkabb csak adatra, es ahol pointered van az == hasznalatanal, ott  tedd ele a *-ot.

2019-11-18 15:44 UTC, hegyhati commented on filesystem.cpp
> +}
Ez tovabbra is nagyon csunya.

2019-11-18 15:44 UTC, hegyhati commented on outputTest
>  User@User:~/
Tessek beletenni a relative path teszteleset is.

2019-11-22 09:33 UTC, hegyhati approved these changes

2019-11-22 09:33 UTC, merged

2019-11-22 09:33 UTC, hegyhati commented
A force push-t azert lehetoleg ne gyakran alkalmazzatok. 
(meg ne hagyjatok 1 honapig stale-ben branchet ;-) )